//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailDispatcher
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ClientMessage", Namespace = "http://schemas.datacontract.org/2004/07/WsMailQueue")]
    public partial class ClientMessage : object
    {

        private string ErrorField;

        private bool SuccessField;

        private MessageModel messageField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.MessageModel message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageModel", Namespace = "http://schemas.datacontract.org/2004/07/MessageDispacherDA.Model")]
    public partial class MessageModel : object
    {

        private string BCCField;

        private string BodyField;

        private string CCField;

        private System.Nullable<int> DeliveryNotificationOptionsField;

        private long IdField;

        private System.Nullable<int> IdClientField;

        private string IpClientField;

        private bool IsHtmlBodyField;

        private MailDispatcher.MessageAttachments[] MessageAttachmentsField;

        private string NameClientField;

        private int PriorityField;

        private string SenderField;

        private string SubjectField;

        private string ToField;

        private string UserCreatedField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BCC
        {
            get
            {
                return this.BCCField;
            }
            set
            {
                this.BCCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CC
        {
            get
            {
                return this.CCField;
            }
            set
            {
                this.CCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliveryNotificationOptions
        {
            get
            {
                return this.DeliveryNotificationOptionsField;
            }
            set
            {
                this.DeliveryNotificationOptionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdClient
        {
            get
            {
                return this.IdClientField;
            }
            set
            {
                this.IdClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpClient
        {
            get
            {
                return this.IpClientField;
            }
            set
            {
                this.IpClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtmlBody
        {
            get
            {
                return this.IsHtmlBodyField;
            }
            set
            {
                this.IsHtmlBodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.MessageAttachments[] MessageAttachments
        {
            get
            {
                return this.MessageAttachmentsField;
            }
            set
            {
                this.MessageAttachmentsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameClient
        {
            get
            {
                return this.NameClientField;
            }
            set
            {
                this.NameClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCreated
        {
            get
            {
                return this.UserCreatedField;
            }
            set
            {
                this.UserCreatedField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageAttachments", Namespace = "http://schemas.datacontract.org/2004/07/MessageDispacherDA")]
    public partial class MessageAttachments : object
    {

        private bool ActiveField;

        private byte[] ContentField;

        private System.Nullable<bool> EmbedImageField;

        private long IdField;

        private long IdMessageField;

        private MailDispatcher.Message MessageField;

        private string extensionField;

        private string nameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EmbedImage
        {
            get
            {
                return this.EmbedImageField;
            }
            set
            {
                this.EmbedImageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdMessage
        {
            get
            {
                return this.IdMessageField;
            }
            set
            {
                this.IdMessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.Message Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Message", Namespace = "http://schemas.datacontract.org/2004/07/MessageDispacherDA")]
    public partial class Message : object
    {

        private bool ActiveField;

        private string BCCField;

        private string BodyField;

        private string CCField;

        private MailDispatcher.Client ClientField;

        private System.Nullable<System.DateTime> DateTimeOfCreationField;

        private System.Nullable<System.DateTime> DateTimeOfUpdateField;

        private System.Nullable<int> DeliveryNotificationOptionsField;

        private long IdField;

        private int IdClientField;

        private int IdMessageStatusField;

        private int IdMessageTypeField;

        private string IpClientField;

        private bool IsHtmlBodyField;

        private MailDispatcher.MessageAttachments[] MessageAttachmentsField;

        private MailDispatcher.MessageStatus MessageStatusField;

        private MailDispatcher.MessageTypes MessageTypesField;

        private string NameField;

        private int NumberOfFailuresField;

        private int PriorityField;

        private string ProcessResultMessageField;

        private string SenderField;

        private string SubjectField;

        private string ToField;

        private string UserCreatedField;

        private string UserModifiedField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BCC
        {
            get
            {
                return this.BCCField;
            }
            set
            {
                this.BCCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CC
        {
            get
            {
                return this.CCField;
            }
            set
            {
                this.CCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.Client Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTimeOfCreation
        {
            get
            {
                return this.DateTimeOfCreationField;
            }
            set
            {
                this.DateTimeOfCreationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTimeOfUpdate
        {
            get
            {
                return this.DateTimeOfUpdateField;
            }
            set
            {
                this.DateTimeOfUpdateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliveryNotificationOptions
        {
            get
            {
                return this.DeliveryNotificationOptionsField;
            }
            set
            {
                this.DeliveryNotificationOptionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdClient
        {
            get
            {
                return this.IdClientField;
            }
            set
            {
                this.IdClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMessageStatus
        {
            get
            {
                return this.IdMessageStatusField;
            }
            set
            {
                this.IdMessageStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMessageType
        {
            get
            {
                return this.IdMessageTypeField;
            }
            set
            {
                this.IdMessageTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpClient
        {
            get
            {
                return this.IpClientField;
            }
            set
            {
                this.IpClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtmlBody
        {
            get
            {
                return this.IsHtmlBodyField;
            }
            set
            {
                this.IsHtmlBodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.MessageAttachments[] MessageAttachments
        {
            get
            {
                return this.MessageAttachmentsField;
            }
            set
            {
                this.MessageAttachmentsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.MessageStatus MessageStatus
        {
            get
            {
                return this.MessageStatusField;
            }
            set
            {
                this.MessageStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.MessageTypes MessageTypes
        {
            get
            {
                return this.MessageTypesField;
            }
            set
            {
                this.MessageTypesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfFailures
        {
            get
            {
                return this.NumberOfFailuresField;
            }
            set
            {
                this.NumberOfFailuresField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessResultMessage
        {
            get
            {
                return this.ProcessResultMessageField;
            }
            set
            {
                this.ProcessResultMessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCreated
        {
            get
            {
                return this.UserCreatedField;
            }
            set
            {
                this.UserCreatedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserModified
        {
            get
            {
                return this.UserModifiedField;
            }
            set
            {
                this.UserModifiedField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Client", Namespace = "http://schemas.datacontract.org/2004/07/MessageDispacherDA")]
    public partial class Client : object
    {

        private bool ActiveField;

        private MailDispatcher.ClientAccountSenders[] ClientAccountSendersField;

        private MailDispatcher.ClientStatus ClientStatusField;

        private MailDispatcher.ClientType ClientTypeField;

        private System.Nullable<bool> GenericoField;

        private int IdField;

        private int IdClientTypeField;

        private int IdStatusField;

        private MailDispatcher.Message[] MessageField;

        private string NameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.ClientAccountSenders[] ClientAccountSenders
        {
            get
            {
                return this.ClientAccountSendersField;
            }
            set
            {
                this.ClientAccountSendersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.ClientStatus ClientStatus
        {
            get
            {
                return this.ClientStatusField;
            }
            set
            {
                this.ClientStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.ClientType ClientType
        {
            get
            {
                return this.ClientTypeField;
            }
            set
            {
                this.ClientTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Generico
        {
            get
            {
                return this.GenericoField;
            }
            set
            {
                this.GenericoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdClientType
        {
            get
            {
                return this.IdClientTypeField;
            }
            set
            {
                this.IdClientTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdStatus
        {
            get
            {
                return this.IdStatusField;
            }
            set
            {
                this.IdStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.Message[] Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageStatus", Namespace = "http://schemas.datacontract.org/2004/07/MessageDispacherDA")]
    public partial class MessageStatus : object
    {

        private bool ActiveField;

        private string CodeField;

        private int IdField;

        private MailDispatcher.Message[] MessageField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.Message[] Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MessageTypes", Namespace = "http://schemas.datacontract.org/2004/07/MessageDispacherDA")]
    public partial class MessageTypes : object
    {

        private bool ActiveField;

        private string CodeField;

        private int IdField;

        private MailDispatcher.Message[] MessageField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.Message[] Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ClientStatus", Namespace = "http://schemas.datacontract.org/2004/07/MessageDispacherDA")]
    public partial class ClientStatus : object
    {

        private MailDispatcher.Client[] ClientField;

        private string CodeField;

        private int IdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.Client[] Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ClientType", Namespace = "http://schemas.datacontract.org/2004/07/MessageDispacherDA")]
    public partial class ClientType : object
    {

        private bool ActiveField;

        private MailDispatcher.Client[] ClientField;

        private string CodeField;

        private int IdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.Client[] Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ClientAccountSenders", Namespace = "http://schemas.datacontract.org/2004/07/MessageDispacherDA")]
    public partial class ClientAccountSenders : object
    {

        private MailDispatcher.AccountSenders AccountSendersField;

        private bool ActiveField;

        private MailDispatcher.Client ClientField;

        private int IdField;

        private int IdAccountSenderField;

        private int IdClientField;

        private int OrderField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.AccountSenders AccountSenders
        {
            get
            {
                return this.AccountSendersField;
            }
            set
            {
                this.AccountSendersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.Client Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAccountSender
        {
            get
            {
                return this.IdAccountSenderField;
            }
            set
            {
                this.IdAccountSenderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdClient
        {
            get
            {
                return this.IdClientField;
            }
            set
            {
                this.IdClientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order
        {
            get
            {
                return this.OrderField;
            }
            set
            {
                this.OrderField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AccountSenders", Namespace = "http://schemas.datacontract.org/2004/07/MessageDispacherDA")]
    public partial class AccountSenders : object
    {

        private string AccountField;

        private bool ActiveField;

        private MailDispatcher.ClientAccountSenders[] ClientAccountSendersField;

        private string DisplayNameField;

        private bool EnableSSLField;

        private string HostField;

        private int IdField;

        private string PasswordField;

        private int PortField;

        private System.Nullable<int> TimeOutField;

        private bool UseDefaultCredentialsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account
        {
            get
            {
                return this.AccountField;
            }
            set
            {
                this.AccountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public MailDispatcher.ClientAccountSenders[] ClientAccountSenders
        {
            get
            {
                return this.ClientAccountSendersField;
            }
            set
            {
                this.ClientAccountSendersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnableSSL
        {
            get
            {
                return this.EnableSSLField;
            }
            set
            {
                this.EnableSSLField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host
        {
            get
            {
                return this.HostField;
            }
            set
            {
                this.HostField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port
        {
            get
            {
                return this.PortField;
            }
            set
            {
                this.PortField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TimeOut
        {
            get
            {
                return this.TimeOutField;
            }
            set
            {
                this.TimeOutField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseDefaultCredentials
        {
            get
            {
                return this.UseDefaultCredentialsField;
            }
            set
            {
                this.UseDefaultCredentialsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ServiceStatus", Namespace = "http://schemas.datacontract.org/2004/07/WsMailQueue")]
    public partial class ServiceStatus : object
    {

        private bool OnLineField;

        private string ResponseField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnLine
        {
            get
            {
                return this.OnLineField;
            }
            set
            {
                this.OnLineField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Response
        {
            get
            {
                return this.ResponseField;
            }
            set
            {
                this.ResponseField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RequestData", Namespace = "http://schemas.datacontract.org/2004/07/WsMailQueue.Models")]
    public partial class RequestData : object
    {

        private string PwdField;

        private string UsnameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pwd
        {
            get
            {
                return this.PwdField;
            }
            set
            {
                this.PwdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usname
        {
            get
            {
                return this.UsnameField;
            }
            set
            {
                this.UsnameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResponseData", Namespace = "http://schemas.datacontract.org/2004/07/WsMailQueue.Models")]
    public partial class ResponseData : object
    {

        private string TokenField;

        private bool AuthenticatedField;

        private string EmployeeIdField;

        private string FirstnameField;

        private System.DateTime TimestampField;

        private string UserNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public bool Authenticated
        {
            get
            {
                return this.AuthenticatedField;
            }
            set
            {
                this.AuthenticatedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string Firstname
        {
            get
            {
                return this.FirstnameField;
            }
            set
            {
                this.FirstnameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "MailDispatcher.IQueue")]
    public interface IQueue
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IQueue/CreateMessage", ReplyAction = "http://tempuri.org/IQueue/CreateMessageResponse")]
        System.Threading.Tasks.Task<MailDispatcher.ClientMessage> CreateMessageAsync(MailDispatcher.ClientMessage message);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IQueue/IsOnline", ReplyAction = "http://tempuri.org/IQueue/IsOnlineResponse")]
        System.Threading.Tasks.Task<MailDispatcher.ServiceStatus> IsOnlineAsync(string request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IQueue/Login", ReplyAction = "http://tempuri.org/IQueue/LoginResponse")]
        System.Threading.Tasks.Task<MailDispatcher.ResponseData> LoginAsync(MailDispatcher.RequestData data);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IQueueChannel : MailDispatcher.IQueue, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class QueueClient : System.ServiceModel.ClientBase<MailDispatcher.IQueue>, MailDispatcher.IQueue
    {

        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public QueueClient() :
                base(QueueClient.GetDefaultBinding(), QueueClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IQueue.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public QueueClient(EndpointConfiguration endpointConfiguration) :
                base(QueueClient.GetBindingForEndpoint(endpointConfiguration), QueueClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public QueueClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(QueueClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public QueueClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(QueueClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public QueueClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<MailDispatcher.ClientMessage> CreateMessageAsync(MailDispatcher.ClientMessage message)
        {
            return base.Channel.CreateMessageAsync(message);
        }

        public System.Threading.Tasks.Task<MailDispatcher.ServiceStatus> IsOnlineAsync(string request)
        {
            return base.Channel.IsOnlineAsync(request);
        }

        public System.Threading.Tasks.Task<MailDispatcher.ResponseData> LoginAsync(MailDispatcher.RequestData data)
        {
            return base.Channel.LoginAsync(data);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IQueue))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IQueue))
            {
                return new System.ServiceModel.EndpointAddress("https://appsdev.cotemar.com.mx/WsMessageQueue/Queue.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return QueueClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IQueue);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return QueueClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IQueue);
        }

        public enum EndpointConfiguration
        {

            BasicHttpBinding_IQueue,
        }
    }
}
